version: '2'
services:
  tester:
    build: test/resources/docker
    volumes:
      - .:/project
      - sbt:/root/.sbt
      - ivy2:/root/.ivy2
    ports:
      - 9000:9000
    command: activator ~run
    environment:
      - DATABASE_SERVER=<fill in>
      - DATABASE_NAME=<fill in>
      - DATABASE_LOGIN=<fill in>
      - DATABASE_PASSWORD=<fill in>
volumes:
  sbt:
    external: true
  ivy2:
    external: true