version: '2'
services:
  tester:
    build: test/resources/docker
    volumes:
      - .:/project
      - sbt:/root/.sbt
      - ivy2:/root/.ivy2
    ports:
      - 9000:9000
    command: activator ~compile
volumes:
  sbt:
    external: true
  ivy2:
    external: true